name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1.7
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: OpenIntelWireless
          base: master
          head: master
          merge_method: rebase
          pr_title: \[ForkSync\] Sync with upstream.